[package]
name = "gw-tools"
version = "0.1.0"
authors = ["Nervos Network"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
env_logger = "0.8"
clap = "2.33"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
toml = "0.5"
bech32 = "0.6.0"
tempfile = "3.2"
lazy_static = "1.3"
secp256k1 = "0.17"
sha3 = "0.9.1"
reqwest = { version = "0.11", features = ["json", "blocking"] }
ckb-jsonrpc-types = "0.38.0"
ckb-types = "0.38.0"
ckb-resource = "0.38.0"
ckb-hash = "0.38.0"
ckb-fixed-hash = "0.38.0"
ckb-sdk = { git = "https://github.com/jjyr/ckb-cli.git", branch = "ckb-v0.38.0" }
gw-db = { path = "../db" }
gw-types = { path = "../types" }
gw-config = { path = "../config" }
gw-common = { path = "../common" }
gw-generator = { path = "../generator" }
gw-jsonrpc-types = { path = "../jsonrpc-types" }
url = "2.2"
faster-hex = "0.5.0"
