[package]
name = "gw-store"
version = "1.8.0-rc1"
authors = ["Nervos Network"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gw-types = { path = "../types" }
gw-config = { path = "../config" }
gw-common = { path = "../common" }
gw-traits = { path = "../traits" }
anyhow = "1.0"
arc-swap = "1.5.0"
log = "0.4"
im = "15.1.0"
autorocks = { git = "https://github.com/sopium/autorocks.git" }
tempfile = "3.3.0"
serde = "1.0.149"

[features]
smt-trie = ["gw-common/smt-trie"]
