name: Batch Deposit&Withdraw

on:
  workflow_dispatch:
    inputs:
      derived:
        description: 'how many derived accounts to use'
        required: true
        default: '10'
        type: string
      claim:
        description: 'claim for derived accounts'
        required: true
        default: true
        type: boolean
      rounds:
        description: 'for-loop rounds'
        required: true
        default: '1'
        type: string
      capacity:
        description: 'deposit/withdraw CKB capacity'
        required: true
        default: '400'
        type: string
      sudt-lock-args:
        description: 'sudt lock_args'
        required: false
        type: string
      sudt-amount:
        description: 'deposit/withdraw sudt amount'
        required: false
        type: string
      sudt-decimals:
        description: 'decimals of sudt amount'
        required: false
        type: string

jobs:
  check-secrets:
    runs-on: ubuntu-latest
    outputs:
      available: ${{ steps.check.outputs.available }}
    steps:
      - id: check
        env:
          KEY1: '${{ secrets.GODWOKEN_TEST_PRIVATE_KEY }}'
        if: ${{ env.KEY1 != '' }}
        run: echo "::set-output name=available::true"

  batch-claim-for-l1:
    needs: check-secrets
    if: needs.check-secrets.outputs.available
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Account-Faucet
        working-directory: scripts/account-faucet
        if: ${{ inputs.claim }}
        run: npm install && npm run build
      - name: Claim for derived accounts
        working-directory: scripts/account-faucet
        if: ${{ inputs.claim }}
        run: |
          account-faucet batch-claim-l1 \
            --private-key ${{ secrets.GODWOKEN_TEST_PRIVATE_KEY }} \
            --derived-count ${{ inputs.derived }} \
            --network alphanet_v1

  batch-actions:
    runs-on: ubuntu-latest
    needs: [check-secrets, batch-claim-for-l1]
    if: needs.check-secrets.outputs.available
    strategy:
      fail-fast: false
      matrix:
        action: [batch-deposit, batch-withdraw]
    steps:
      - uses: actions/checkout@v2

      - name: Setup Light-Godwoken-CLI
        working-directory: scripts/light-godwoken-cli
        run: ./init.sh

      - name: Create batch action
        working-directory: scripts/light-godwoken-cli
        run: |
          for _ in $(seq 1 ${{ inputs.rounds }})
          do
            echo "[${{ matrix.action }}] round $_"
            lgc ${{ matrix.action }} \
              --private-key ${{ secrets.GODWOKEN_TESTNET_PK1 }} \
              --derived-count ${{ inputs.derived }} \
              --capacity ${{ inputs.capacity }} \
              --sudt-lock-args "${{ inputs.sudt-lock-args }}" \
              --sudt-amount "${{ inputs.sudt-amount }}" \
              --sudt-decimals "${{ inputs.sudt-decimals }}" \
              --network alphanet_v1;
            echo "---"
            sleep 10s
          done
