name: Batch Prepare For Batch Transactions

on:
  workflow_dispatch

jobs:
  check-secrets:
    runs-on: ubuntu-latest
    outputs:
      available: ${{ steps.check.outputs.available }}
    steps:
      - id: check
        env:
          KEY1: '${{ secrets.GODWOKEN_TEST_PRIVATE_KEY }}'
        if: ${{ env.KEY1 != '' }}
        run: echo "::set-output name=available::true"

  batch-claim:
    needs: check-secrets
    if: needs.check-secrets.outputs.available
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: scripts/account-faucet/package-lock.json

      - name: Setup Account-Faucet
        working-directory: scripts/account-faucet
        run: npm i && npm run build

      - name: Claim for derived accounts on L1
        working-directory: scripts/account-faucet
        run: |
          account-faucet batch-claim-l1 \
            --private-key ${{ secrets.GODWOKEN_TEST_PRIVATE_KEY }} \
            --network alphanet_v1

      - name: Claim for derived accounts on L2
        working-directory: scripts/account-faucet
        run: |
          account-faucet batch-claim-l2 \
            --private-key ${{ secrets.GODWOKEN_TEST_PRIVATE_KEY }} \
            --network alphanet_v1

  batch-prepare:
    runs-on: ubuntu-latest
    needs: [check-secrets, batch-claim]
    if: needs.check-secrets.outputs.available
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Setup Light-Godwoken-CLI
        working-directory: scripts/light-godwoken-cli
        run: ./init.sh

      - name: Run batch-prepare
        working-directory: scripts/light-godwoken-cli
        run: |
          lgc batch-prepare \
            --private-key ${{ secrets.GODWOKEN_TEST_PRIVATE_KEY }} \
            --network alphanet_v1

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: batch-prepare
          path: ${{ github.workspace }}/scripts/light-godwoken-cli/artifacts
